export const locals: {
	fa: string
	faLg: string
	fa2X: string
	fa3X: string
	fa4X: string
	fa5X: string
	faFw: string
	faUl: string
	faLi: string
	faBorder: string
	faPullLeft: string
	faPullRight: string
	pullRight: string
	pullLeft: string
	faSpin: string
	faPulse: string
	faRotate90: string
	faRotate180: string
	faRotate270: string
	faFlipHorizontal: string
	faFlipVertical: string
	faStack: string
	faStack1X: string
	faStack2X: string
	faInverse: string
	faGlass: string
	faMusic: string
	faSearch: string
	faEnvelopeO: string
	faHeart: string
	faStar: string
	faStarO: string
	faUser: string
	faFilm: string
	faThLarge: string
	faTh: string
	faThList: string
	faCheck: string
	faRemove: string
	faClose: string
	faTimes: string
	faSearchPlus: string
	faSearchMinus: string
	faPowerOff: string
	faSignal: string
	faGear: string
	faCog: string
	faTrashO: string
	faHome: string
	faFileO: string
	faClockO: string
	faRoad: string
	faDownload: string
	faArrowCircleODown: string
	faArrowCircleOUp: string
	faInbox: string
	faPlayCircleO: string
	faRotateRight: string
	faRepeat: string
	faRefresh: string
	faListAlt: string
	faLock: string
	faFlag: string
	faHeadphones: string
	faVolumeOff: string
	faVolumeDown: string
	faVolumeUp: string
	faQrcode: string
	faBarcode: string
	faTag: string
	faTags: string
	faBook: string
	faBookmark: string
	faPrint: string
	faCamera: string
	faFont: string
	faBold: string
	faItalic: string
	faTextHeight: string
	faTextWidth: string
	faAlignLeft: string
	faAlignCenter: string
	faAlignRight: string
	faAlignJustify: string
	faList: string
	faDedent: string
	faOutdent: string
	faIndent: string
	faVideoCamera: string
	faPhoto: string
	faImage: string
	faPictureO: string
	faPencil: string
	faMapMarker: string
	faAdjust: string
	faTint: string
	faEdit: string
	faPencilSquareO: string
	faShareSquareO: string
	faCheckSquareO: string
	faArrows: string
	faStepBackward: string
	faFastBackward: string
	faBackward: string
	faPlay: string
	faPause: string
	faStop: string
	faForward: string
	faFastForward: string
	faStepForward: string
	faEject: string
	faChevronLeft: string
	faChevronRight: string
	faPlusCircle: string
	faMinusCircle: string
	faTimesCircle: string
	faCheckCircle: string
	faQuestionCircle: string
	faInfoCircle: string
	faCrosshairs: string
	faTimesCircleO: string
	faCheckCircleO: string
	faBan: string
	faArrowLeft: string
	faArrowRight: string
	faArrowUp: string
	faArrowDown: string
	faMailForward: string
	faShare: string
	faExpand: string
	faCompress: string
	faPlus: string
	faMinus: string
	faAsterisk: string
	faExclamationCircle: string
	faGift: string
	faLeaf: string
	faFire: string
	faEye: string
	faEyeSlash: string
	faWarning: string
	faExclamationTriangle: string
	faPlane: string
	faCalendar: string
	faRandom: string
	faComment: string
	faMagnet: string
	faChevronUp: string
	faChevronDown: string
	faRetweet: string
	faShoppingCart: string
	faFolder: string
	faFolderOpen: string
	faArrowsV: string
	faArrowsH: string
	faBarChartO: string
	faBarChart: string
	faTwitterSquare: string
	faFacebookSquare: string
	faCameraRetro: string
	faKey: string
	faGears: string
	faCogs: string
	faComments: string
	faThumbsOUp: string
	faThumbsODown: string
	faStarHalf: string
	faHeartO: string
	faSignOut: string
	faLinkedinSquare: string
	faThumbTack: string
	faExternalLink: string
	faSignIn: string
	faTrophy: string
	faGithubSquare: string
	faUpload: string
	faLemonO: string
	faPhone: string
	faSquareO: string
	faBookmarkO: string
	faPhoneSquare: string
	faTwitter: string
	faFacebookF: string
	faFacebook: string
	faGithub: string
	faUnlock: string
	faCreditCard: string
	faFeed: string
	faRss: string
	faHddO: string
	faBullhorn: string
	faBell: string
	faCertificate: string
	faHandORight: string
	faHandOLeft: string
	faHandOUp: string
	faHandODown: string
	faArrowCircleLeft: string
	faArrowCircleRight: string
	faArrowCircleUp: string
	faArrowCircleDown: string
	faGlobe: string
	faWrench: string
	faTasks: string
	faFilter: string
	faBriefcase: string
	faArrowsAlt: string
	faGroup: string
	faUsers: string
	faChain: string
	faLink: string
	faCloud: string
	faFlask: string
	faCut: string
	faScissors: string
	faCopy: string
	faFilesO: string
	faPaperclip: string
	faSave: string
	faFloppyO: string
	faSquare: string
	faNavicon: string
	faReorder: string
	faBars: string
	faListUl: string
	faListOl: string
	faStrikethrough: string
	faUnderline: string
	faTable: string
	faMagic: string
	faTruck: string
	faPinterest: string
	faPinterestSquare: string
	faGooglePlusSquare: string
	faGooglePlus: string
	faMoney: string
	faCaretDown: string
	faCaretUp: string
	faCaretLeft: string
	faCaretRight: string
	faColumns: string
	faUnsorted: string
	faSort: string
	faSortDown: string
	faSortDesc: string
	faSortUp: string
	faSortAsc: string
	faEnvelope: string
	faLinkedin: string
	faRotateLeft: string
	faUndo: string
	faLegal: string
	faGavel: string
	faDashboard: string
	faTachometer: string
	faCommentO: string
	faCommentsO: string
	faFlash: string
	faBolt: string
	faSitemap: string
	faUmbrella: string
	faPaste: string
	faClipboard: string
	faLightbulbO: string
	faExchange: string
	faCloudDownload: string
	faCloudUpload: string
	faUserMd: string
	faStethoscope: string
	faSuitcase: string
	faBellO: string
	faCoffee: string
	faCutlery: string
	faFileTextO: string
	faBuildingO: string
	faHospitalO: string
	faAmbulance: string
	faMedkit: string
	faFighterJet: string
	faBeer: string
	faHSquare: string
	faPlusSquare: string
	faAngleDoubleLeft: string
	faAngleDoubleRight: string
	faAngleDoubleUp: string
	faAngleDoubleDown: string
	faAngleLeft: string
	faAngleRight: string
	faAngleUp: string
	faAngleDown: string
	faDesktop: string
	faLaptop: string
	faTablet: string
	faMobilePhone: string
	faMobile: string
	faCircleO: string
	faQuoteLeft: string
	faQuoteRight: string
	faSpinner: string
	faCircle: string
	faMailReply: string
	faReply: string
	faGithubAlt: string
	faFolderO: string
	faFolderOpenO: string
	faSmileO: string
	faFrownO: string
	faMehO: string
	faGamepad: string
	faKeyboardO: string
	faFlagO: string
	faFlagCheckered: string
	faTerminal: string
	faCode: string
	faMailReplyAll: string
	faReplyAll: string
	faStarHalfEmpty: string
	faStarHalfFull: string
	faStarHalfO: string
	faLocationArrow: string
	faCrop: string
	faCodeFork: string
	faUnlink: string
	faChainBroken: string
	faQuestion: string
	faInfo: string
	faExclamation: string
	faSuperscript: string
	faSubscript: string
	faEraser: string
	faPuzzlePiece: string
	faMicrophone: string
	faMicrophoneSlash: string
	faShield: string
	faCalendarO: string
	faFireExtinguisher: string
	faRocket: string
	faMaxcdn: string
	faChevronCircleLeft: string
	faChevronCircleRight: string
	faChevronCircleUp: string
	faChevronCircleDown: string
	faHtml5: string
	faCss3: string
	faAnchor: string
	faUnlockAlt: string
	faBullseye: string
	faEllipsisH: string
	faEllipsisV: string
	faRssSquare: string
	faPlayCircle: string
	faTicket: string
	faMinusSquare: string
	faMinusSquareO: string
	faLevelUp: string
	faLevelDown: string
	faCheckSquare: string
	faPencilSquare: string
	faExternalLinkSquare: string
	faShareSquare: string
	faCompass: string
	faToggleDown: string
	faCaretSquareODown: string
	faToggleUp: string
	faCaretSquareOUp: string
	faToggleRight: string
	faCaretSquareORight: string
	faEuro: string
	faEur: string
	faGbp: string
	faDollar: string
	faUsd: string
	faRupee: string
	faInr: string
	faCny: string
	faRmb: string
	faYen: string
	faJpy: string
	faRuble: string
	faRouble: string
	faRub: string
	faWon: string
	faKrw: string
	faBitcoin: string
	faBtc: string
	faFile: string
	faFileText: string
	faSortAlphaAsc: string
	faSortAlphaDesc: string
	faSortAmountAsc: string
	faSortAmountDesc: string
	faSortNumericAsc: string
	faSortNumericDesc: string
	faThumbsUp: string
	faThumbsDown: string
	faYoutubeSquare: string
	faYoutube: string
	faXing: string
	faXingSquare: string
	faYoutubePlay: string
	faDropbox: string
	faStackOverflow: string
	faInstagram: string
	faFlickr: string
	faAdn: string
	faBitbucket: string
	faBitbucketSquare: string
	faTumblr: string
	faTumblrSquare: string
	faLongArrowDown: string
	faLongArrowUp: string
	faLongArrowLeft: string
	faLongArrowRight: string
	faApple: string
	faWindows: string
	faAndroid: string
	faLinux: string
	faDribbble: string
	faSkype: string
	faFoursquare: string
	faTrello: string
	faFemale: string
	faMale: string
	faGittip: string
	faGratipay: string
	faSunO: string
	faMoonO: string
	faArchive: string
	faBug: string
	faVk: string
	faWeibo: string
	faRenren: string
	faPagelines: string
	faStackExchange: string
	faArrowCircleORight: string
	faArrowCircleOLeft: string
	faToggleLeft: string
	faCaretSquareOLeft: string
	faDotCircleO: string
	faWheelchair: string
	faVimeoSquare: string
	faTurkishLira: string
	faTry: string
	faPlusSquareO: string
	faSpaceShuttle: string
	faSlack: string
	faEnvelopeSquare: string
	faWordpress: string
	faOpenid: string
	faInstitution: string
	faBank: string
	faUniversity: string
	faMortarBoard: string
	faGraduationCap: string
	faYahoo: string
	faGoogle: string
	faReddit: string
	faRedditSquare: string
	faStumbleuponCircle: string
	faStumbleupon: string
	faDelicious: string
	faDigg: string
	faPiedPiper: string
	faPiedPiperAlt: string
	faDrupal: string
	faJoomla: string
	faLanguage: string
	faFax: string
	faBuilding: string
	faChild: string
	faPaw: string
	faSpoon: string
	faCube: string
	faCubes: string
	faBehance: string
	faBehanceSquare: string
	faSteam: string
	faSteamSquare: string
	faRecycle: string
	faAutomobile: string
	faCar: string
	faCab: string
	faTaxi: string
	faTree: string
	faSpotify: string
	faDeviantart: string
	faSoundcloud: string
	faDatabase: string
	faFilePdfO: string
	faFileWordO: string
	faFileExcelO: string
	faFilePowerpointO: string
	faFilePhotoO: string
	faFilePictureO: string
	faFileImageO: string
	faFileZipO: string
	faFileArchiveO: string
	faFileSoundO: string
	faFileAudioO: string
	faFileMovieO: string
	faFileVideoO: string
	faFileCodeO: string
	faVine: string
	faCodepen: string
	faJsfiddle: string
	faLifeBouy: string
	faLifeBuoy: string
	faLifeSaver: string
	faSupport: string
	faLifeRing: string
	faCircleONotch: string
	faRa: string
	faRebel: string
	faGe: string
	faEmpire: string
	faGitSquare: string
	faGit: string
	faYCombinatorSquare: string
	faYcSquare: string
	faHackerNews: string
	faTencentWeibo: string
	faQq: string
	faWechat: string
	faWeixin: string
	faSend: string
	faPaperPlane: string
	faSendO: string
	faPaperPlaneO: string
	faHistory: string
	faCircleThin: string
	faHeader: string
	faParagraph: string
	faSliders: string
	faShareAlt: string
	faShareAltSquare: string
	faBomb: string
	faSoccerBallO: string
	faFutbolO: string
	faTty: string
	faBinoculars: string
	faPlug: string
	faSlideshare: string
	faTwitch: string
	faYelp: string
	faNewspaperO: string
	faWifi: string
	faCalculator: string
	faPaypal: string
	faGoogleWallet: string
	faCcVisa: string
	faCcMastercard: string
	faCcDiscover: string
	faCcAmex: string
	faCcPaypal: string
	faCcStripe: string
	faBellSlash: string
	faBellSlashO: string
	faTrash: string
	faCopyright: string
	faAt: string
	faEyedropper: string
	faPaintBrush: string
	faBirthdayCake: string
	faAreaChart: string
	faPieChart: string
	faLineChart: string
	faLastfm: string
	faLastfmSquare: string
	faToggleOff: string
	faToggleOn: string
	faBicycle: string
	faBus: string
	faIoxhost: string
	faAngellist: string
	faCc: string
	faShekel: string
	faSheqel: string
	faIls: string
	faMeanpath: string
	faBuysellads: string
	faConnectdevelop: string
	faDashcube: string
	faForumbee: string
	faLeanpub: string
	faSellsy: string
	faShirtsinbulk: string
	faSimplybuilt: string
	faSkyatlas: string
	faCartPlus: string
	faCartArrowDown: string
	faDiamond: string
	faShip: string
	faUserSecret: string
	faMotorcycle: string
	faStreetView: string
	faHeartbeat: string
	faVenus: string
	faMars: string
	faMercury: string
	faIntersex: string
	faTransgender: string
	faTransgenderAlt: string
	faVenusDouble: string
	faMarsDouble: string
	faVenusMars: string
	faMarsStroke: string
	faMarsStrokeV: string
	faMarsStrokeH: string
	faNeuter: string
	faGenderless: string
	faFacebookOfficial: string
	faPinterestP: string
	faWhatsapp: string
	faServer: string
	faUserPlus: string
	faUserTimes: string
	faHotel: string
	faBed: string
	faViacoin: string
	faTrain: string
	faSubway: string
	faMedium: string
	faYc: string
	faYCombinator: string
	faOptinMonster: string
	faOpencart: string
	faExpeditedssl: string
	faBattery4: string
	faBatteryFull: string
	faBattery3: string
	faBatteryThreeQuarters: string
	faBattery2: string
	faBatteryHalf: string
	faBattery1: string
	faBatteryQuarter: string
	faBattery0: string
	faBatteryEmpty: string
	faMousePointer: string
	faICursor: string
	faObjectGroup: string
	faObjectUngroup: string
	faStickyNote: string
	faStickyNoteO: string
	faCcJcb: string
	faCcDinersClub: string
	faClone: string
	faBalanceScale: string
	faHourglassO: string
	faHourglass1: string
	faHourglassStart: string
	faHourglass2: string
	faHourglassHalf: string
	faHourglass3: string
	faHourglassEnd: string
	faHourglass: string
	faHandGrabO: string
	faHandRockO: string
	faHandStopO: string
	faHandPaperO: string
	faHandScissorsO: string
	faHandLizardO: string
	faHandSpockO: string
	faHandPointerO: string
	faHandPeaceO: string
	faTrademark: string
	faRegistered: string
	faCreativeCommons: string
	faGg: string
	faGgCircle: string
	faTripadvisor: string
	faOdnoklassniki: string
	faOdnoklassnikiSquare: string
	faGetPocket: string
	faWikipediaW: string
	faSafari: string
	faChrome: string
	faFirefox: string
	faOpera: string
	faInternetExplorer: string
	faTv: string
	faTelevision: string
	faContao: string
	fa500Px: string
	faAmazon: string
	faCalendarPlusO: string
	faCalendarMinusO: string
	faCalendarTimesO: string
	faCalendarCheckO: string
	faIndustry: string
	faMapPin: string
	faMapSigns: string
	faMapO: string
	faMap: string
	faCommenting: string
	faCommentingO: string
	faHouzz: string
	faVimeo: string
	faBlackTie: string
	faFonticons: string
	faRedditAlien: string
	faEdge: string
	faCreditCardAlt: string
	faCodiepie: string
	faModx: string
	faFortAwesome: string
	faUsb: string
	faProductHunt: string
	faMixcloud: string
	faScribd: string
	faPauseCircle: string
	faPauseCircleO: string
	faStopCircle: string
	faStopCircleO: string
	faShoppingBag: string
	faShoppingBasket: string
	faHashtag: string
	faBluetooth: string
	faBluetoothB: string
	faPercent: string
	faGitlab: string
	faWpbeginner: string
	faWpforms: string
	faEnvira: string
	faUniversalAccess: string
	faWheelchairAlt: string
	faQuestionCircleO: string
	faBlind: string
	faAudioDescription: string
	faVolumeControlPhone: string
	faBraille: string
	faAssistiveListeningSystems: string
	faAslInterpreting: string
	faAmericanSignLanguageInterpreting: string
	faDeafness: string
	faHardOfHearing: string
	faDeaf: string
	faGlide: string
	faGlideG: string
	faSigning: string
	faSignLanguage: string
	faLowVision: string
	faViadeo: string
	faViadeoSquare: string
	faSnapchat: string
	faSnapchatGhost: string
	faSnapchatSquare: string
	srOnly: string
	srOnlyFocusable: string
}